@Choix_des_technos_et_infras_de_développement___TP3_HostAddress = http://localhost:5296

GET {{Choix_des_technos_et_infras_de_développement___TP3_HostAddress}}/weatherforecast/
Accept: application/json

###
